### ISSUE TITLE
DOM Datastructure

### ISSUE THREAD

**Issue by burner** [lodo1995/experimental.xml#9]
https://github.com/lodo1995/experimental.xml/blob/master/source/std/experimental/xml/dom.d

I know classes are the obvious choice here. But I think that will diminish the acceptance of the xml library as a hole. Maybe look into a RefCounted approach or flatting the tree into an array.

**Comment by lodo1995** [comment]
My main motivation for using classes is not reference semantics, but polymorphism. Changing the classes to structs means adding a `kind` field, and every method would then have a big if-elseif-else to implement a different behaviour for each possible kind. I think this approach is neither maintainable nor extensible.

I suppose that avoiding virtual functions and gc allocations are the main motivations for avoiding classes. I think that if one needs this kind of control, then he surely doesn't want the entire DOM loaded in memory, but rather an incremental approach (like direct use of a cursor, or use of an InputRange built on top of a cursor, or an event-driven approach).

Another note: I was planning to substitute the current DOM stub with a more feature-complete implementation of the DOM specification, which I already started implementing.

**Comment by burner** [comment]
have a look http://www.ustream.tv/recorded/86424059/highlight/699215
he has a nice bit about polymorphism with structs. 

I get where you are coming, but there are three things to consider.
1. Andrei and Walter agreed that phobos should be GC free in the future. If that means no classes of ref counting is pretty unclear so far. But why take the risk.
2. You saying use an InputRange or Cursor directly is taking the choice away from the user. And people don't like that. I did something similar with std.logger and it is still in experimental.
3. With the thing out of the video you can do polymorphism without classes. Why not do it if the disadvantages are negligible.

About your choice. I'm your mentor, feel free to ignore me. Prototype and test. There is properly no perfect choice.

**Comment by lodo1995** [comment]
Ok. This can be done. If we implement this, then the gc no longer "owns" the nodes, and we have to decide what owns them. I see two possible options:
- the document owns all nodes (in a big array); each node contains a raw pointer to its parent, children, siblings, ...;
- each Node owns its children; the document is a normal node, and owns only the first-level nodes.

Each method has its advantages (the first one allows faster manipulation of the tree, because we can move nodes in the tree without actually copying them, while the second allows easier deallocation of nodes logically removed from the tree) and drawbacks (the first uses lots of raw pointers and loses some memory safety, the second makes it more difficult to access siblings and move nodes around).

Or we just wrap everything with RefCounted, that does the job for us.
